services:
  postgres:
    image: postgres:16-alpine
    container_name: studyplanner-db
    environment:
      POSTGRES_DB: studyplanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studyplanner-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studyplanner
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: dGhpc2lzYXZlcnlzZWN1cmVqd3RzZWNyZXRrZXlmb3JzdHVkeXBsYW5uZXI=
      APP_JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studyplanner-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
