###############################################################
# docker-compose.prod.yml
# Production compose – pulls images from ECR instead of building
###############################################################

services:


  backend:
    image: ${DOCKERHUB_BACKEND}:${IMAGE_TAG:-latest}
    container_name: studyplanner-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-studyplanner}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_JWT_SECRET:             ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION:         ${APP_JWT_EXPIRATION:-86400000}
      SPRING_PROFILES_ACTIVE:     prod

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${DOCKERHUB_FRONTEND}:${IMAGE_TAG:-latest}
    container_name: studyplanner-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

